package nl.voidgroup.gradle.plugin.opengmph.task;

import nl.voidgroup.gradle.plugin.opengmph.Logger;
import nl.voidgroup.gradle.plugin.opengmph.OpenGMPH;
import nl.voidgroup.gradle.plugin.opengmph.Util;
import nl.voidgroup.gradle.plugin.opengmph.data.YMLObject;
import nl.voidgroup.gradle.plugin.opengmph.data.bukkit.BukkitYMLGenHandler;
import nl.voidgroup.gradle.plugin.opengmph.data.minecraft.MinecraftServer;
import nl.voidgroup.gradle.plugin.opengmph.extension.PluginData;
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.nio.charset.StandardCharsets;

public class YMLGen extends DefaultTask {

    public static final String HEADER = "File Generated by ${name}@${version}";

    public YMLGen() {
        shouldRunAfter("processResources");
    }

    @TaskAction
    public void run() throws IOException, NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
        PluginData pluginData = getProject().getExtensions().getByType(PluginData.class);
        MinecraftServer targetServer = Util.requireNonNull(MinecraftServer.getByName(Util.requireNonNull(pluginData.targetServer, "Target server not set")), "Invalid target server");
        if(!targetServer.getClass().isAnnotationPresent(nl.voidgroup.gradle.plugin.opengmph.annotation.YMLGen.class)) {
            throw new UnsupportedOperationException("Current target server does not support yml generation");
        }
        nl.voidgroup.gradle.plugin.opengmph.annotation.YMLGen serverGenData = targetServer.getClass().getAnnotation(nl.voidgroup.gradle.plugin.opengmph.annotation.YMLGen.class);
        File buildResourcesDir = new File((pluginData.buildResourcesDir != null ? pluginData.buildResourcesDir : getProject().getBuildDir().getAbsolutePath() + "/resources"));
        String sourceSet = pluginData.sourceSet;
        String ymlName = serverGenData.file();
        File ymlFile = new File(buildResourcesDir.getAbsolutePath() + "/" + sourceSet + "/" + ymlName);
        ymlFile.getParentFile().mkdirs();
        ymlFile.createNewFile();
        Class<?> genHandlerClass = serverGenData.handler();
        Constructor<?> genHandlerConstructor = genHandlerClass.getDeclaredConstructor();
        BukkitYMLGenHandler genHandler = (BukkitYMLGenHandler) genHandlerConstructor.newInstance();
        YMLObject data = genHandler.generate(pluginData);
        FileOutputStream ymlOutput = new FileOutputStream(ymlFile);
        String ymlText = "# " + HEADER.replace("${name}", OpenGMPH.name).replace("${version}", OpenGMPH.version).replace("\n", "\n# ") + "\n" +
                data.getStr(0);
        ymlOutput.write(ymlText.getBytes(StandardCharsets.UTF_8));
        ymlOutput.close();
    }

}
